// STORAGE
// EL NAVEGADOR PERMITE ALMACENAR INFORMACIÓN PARA MEJORAR LA EXPERIENCIA DE USUARIO
// ENTRE OTRAS COSAS, ESTO PERMITE MANTENER AL USUARIO LOGUEADO, MANTENER EL MODO OSCURO, ETC

// SIMILAR A LAS COOKIES. LA DIFERENCIA ES QUE LAS COOKIES ALMACENAN HASTA 2KBS DE INFORMACION, MIENTRAS QUE LOCALSTORAGE PUEDO GUARDAR HASTA 5MB. TAMBIÉN LAS COOKIES TIENEN OPCIÓN DE TIEMPO. EL LOCALSTORAGE UNA VEZ SE ALMACENA QUEDA GUARDADO. LAS COOKIES SE RENDERIZAN DESDE EL SERVIDOR Y NO DESDE EL NAVEGADOR

// LOCALSTORAGE
// SE UTILIZA SETITEM. localStorage.setItem('llave', contenido)

// TIP !! me permite identificar si existe una variable
// !!nombre = true
// !!undefined = false

//DIFERENCIAS ENTRE LOCALSTORAGE Y SESSIONSTORAGE. SESSION SOLO HACE REFERENCIA A LA PESTAÑA. SOLAMENTE EXISTE DENTRO DE LA PESTAÑA

// JSON ES UN OBJETO DE FORMATO TEXTO PLANO. ES UN STRING CON UN FORMATO ESPECÍFICO.

// CONVERSIÓN DE / HACIA JSON

// STRINGIFY. convierte un objeto JS a un string en formato JSON.

// const enJSON = JSON.stringify(producto)

// PARSE. convierte JSON a objeto de JS.
// const objetoRecuperado = JSON.parse(localStorage.getItem('producto'))